### ISSUE TITLE
interaction detection method: hydrophobic interaction chromatography (HIC)

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#368]
New term needed to annotate eg PMID:9261073. 

Reported by: lukasz99

**Comment by pporrasebi** [comment]
Checked reference PMID and it looks like this could be just dealt with 'reverse phase chromatography'. Lukasz, can you confirm you are happy with this solution?

**Comment by pporrasebi** [comment]
Posting reply from Lukasz:

"On 04/23/2019 03:39 AM, Pablo Porras Millan wrote:
> Hi Lukasz,
>
> Another one. Can you have a look at this one, please? https://github.com/HUPO-PSI/psi-mi-CV/issues/368 I think the column used is just another variation of a reverse phase chromatography column.

columns are similar (sort of) but otherwise the experimental setup is
quite different - typically, in reversed phase low pH and a gradient of water/organic solvent (eg acetonitrile) is used to elute. hic is done at
physiological pH and salt gradient (decreasing concentration) is used
to elute stuff. in effect reversed phase won't work as interaction detection method whereas hic has a chance...

on a practical side reversed phase requires HPLC, HIC can be done at medium/low pressures - Boologic, Acta, etc...

see, eg:

 http://wolfson.huji.ac.il/purification/PDF/HCIC/AMERSHAM_HIC_RPC.pdf

for more details.

lukasz"
