### ISSUE TITLE
new Cv term please:non-denaturing SDS-PAGE

### ISSUE THREAD

**Issue by sodoff** [HUPO-PSI/psi-mi-CV#390]
"non-denaturing SDS-PAGE"
Sandra suggested this be added (see shiroishi-2006-2;pmid:16455647) -presumably as a child of "electrophoresis"?
[I can see why you have used electrophoresis but I think this part of the hierarchy needs rearranging slightly and a term added for non-denaturing SDS-PAGE. ]

**Comment by pporrasebi** [comment]
The experiment shown as a reference is not a non-denaturing SDS-PAGe, but an non-reducing SDS-PAGE. Actually, I do not think you can have a non-denaturing SDS-PAGE, since given the presence of SDS and the boiling step pre-loading to the gel, proteins are going to be denaturalized to some extent. I do not think a new term is required in this case.
