### ISSUE TITLE
Inconsistent MI Code Format in psi-mi.obo

### ISSUE THREAD

**Issue by bmlaw** [HUPO-PSI/psi-mi-CV#452]
Recent additions to the psi-mi.obo file have added new MI codes using an underscore instead of a colon. Is there a reason for this format change in MI ID codes?

**Comment by luanalicata** [comment]
Hi,Thank you for reporting the error.This week i am on holiday, I will check and fix the problem next week.All the bestLuanaIl giorno 27 giu 2023, alle ore 00:33, bmlaw ***@***.***> ha scritto:﻿
Recent additions to the psi-mi.obo file have added new MI codes using an underscore instead of a colon. Is there a reason for this format change in MI ID codes?

**Comment by luanalicata** [comment]
I corrected the error but nothing changed in the obo file and once I open again Protégé, the term is again with an underscore instead of a colon.
I actually noted that all the terms from MI:2412 to 2422 have the same problem.
Any suggestions on how to fix the problem?
Thanks
Luana

**Comment by bmlaw** [comment]
I wouldn't know. I don't use Protege. I just use a text editor.
